name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
  
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Build
      run: |
        npm i
        npm run build
      
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: rumo.cf
        path: dist/*
